import TextEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/Text/Editable';
import ImageEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/Image/Editable';
import ButtonEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/Button/Editable';
import VideoEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/Video/Editable';
import BannerEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/Banner/Editable';
import SliderEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/Slider/Editable';
import BannerTitleEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/BannerTitle/Editable';
import SliderTitleEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/ClassTitle/Editable';
import SliderAuthorEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/ClassAuthor/Editable';
import SliderDescriptionEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/ClassDescription/Editable';
import ClassButtonEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/ClassButton/Editable';
import ClassEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/Class/Editable';
import BulletsEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/Bullets/Editable';
import BulletEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/Bullet/Editable';
import FaqEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/FAQ/Editable';
import QuestionEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/SubComponents/Question/Editable';
import QuestionAnswerEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/SubComponents/QuestionAnswer/Editable';
import AnswerEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/SubComponents/Answer/Editable';
import CustomCodeTextEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/SubComponents/CustomCodeText/Editable';
import CustomCodeEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/CustomCode/Editable';
import CallToActionEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/CallToAction/Editable';
import SubTextEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/SubComponents/Text/Editable';
import SubTextAreaEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/SubComponents/TextArea/Editable';
import SubButtonEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/SubComponents/Button/Editable';
import SubVideoEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/SubComponents/Video/Editable';
import VideoSectionEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/VideoSection/Editable';
import CountDownEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/CountDown/Editable';
import TimerEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/SubComponents/Timer/Editable';
import LinksEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/Links/Editable';
import LinkEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/Link/Editable';
import ClassCardEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/ClassCard/Editable';
import HeroDefaultSectionEditable from 'views/pages/Offers/components/HeroDefaultSection/HeroDefaultSectionEditable';
import DividerEditable from 'views/pages/SchoolRoomTheme/SchoolRoomComponents/Divider/Editable';

const EditableComponents = (type) => {
   const showComponentByType = () => {
      let Component = Text;
      switch (type) {
         case 'button': Component = ButtonEditable;
            break;
         case 'divider': Component = DividerEditable;
            break;
         case 'slider_button': Component = ClassButtonEditable;
            break;
         case 'slider_title': Component = SliderTitleEditable;
            break;
         case 'slider_description': Component = SliderDescriptionEditable;
            break;
         case 'slider_author': Component = SliderAuthorEditable;
            break;
         case 'image': Component = ImageEditable;
            break;
         case 'text': Component = TextEditable;
            break;
         case 'class_card': Component = ClassCardEditable;
            break;
         case 'sub_text': Component = SubTextEditable;
            break;
         case 'sub_textarea': Component = SubTextAreaEditable;
            break;
         case 'sub_button': Component = SubButtonEditable;
            break;
         case 'video': Component = VideoEditable;
            break;
         case 'banner': Component = BannerEditable;
            break;
         case 'slider': Component = SliderEditable;
            break;
         case 'class': Component = ClassEditable;
            break;
         case 'bullets': Component = BulletsEditable;
            break;
         case 'bullet': Component = BulletEditable;
            break;
         case 'links': Component = LinksEditable;
            break;
         case 'link': Component = LinkEditable;
            break;
         case 'banner_title': Component = BannerTitleEditable;
            break;
         case 'FAQ': Component = FaqEditable;
            break;
         case 'questionanswer': Component = QuestionAnswerEditable;
            break;
         case 'question': Component = QuestionEditable;
            break;
         case 'answer': Component = AnswerEditable;
            break;
         case 'customcode': Component = CustomCodeEditable;
            break;
         case 'calltoaction': Component = CallToActionEditable;
            break;
         case 'videosection': Component = VideoSectionEditable;
            break;
         case 'sub_video': Component = SubVideoEditable;
            break;
         case 'timer': Component = TimerEditable;
            break;
         case 'countdown': Component = CountDownEditable;
            break;
         case 'customcode_subcomponent': Component = CustomCodeTextEditable;
            break;
         case 'hero_left_section': Component = HeroDefaultSectionEditable;
            break;
         default: Component = TextEditable;
      }
      return Component;
   };
   return (
      showComponentByType()
   );
};

export default EditableComponents;
