export default {
   GENERATE_INITIAL_STATE: 'useForm/GENERATE_INITIAL_STATE',
   INPUT_CHANGE: 'useForm/INPUT_CHANGE',
   FORM_REQUEST_START: 'useForm/FORM_REQUEST_START',
   FORM_REQUEST_SUCCESS: 'useForm/FORM_REQUEST_SUCCESS',
   FORM_REQUEST_FAIL: 'useForm/FORM_REQUEST_FAIL',
   CANCEL_CHANGES: 'useForm/CANCEL_CHANGES',
   SAVE_FORM_STATE_TO_CACHE: 'useForm/SAVE_FORM_STATE_TO_CACHE',
};
