/* eslint-disable global-require */
const slug = () => {
   function s4() {
      return new Date().getTime() + Math.floor(Math.random() * 1000000);
   }
   return `miestro-${ s4() }`;
};

const state = {
   landing_name: 'landing_13',
   landing_metas: {
      landing_favicon: 'https://miestro-production.s3-us-west-2.amazonaws.com/landing/favico.ico',
      heading_font: 'Inter-Black',
      regular_font: 'Inter-Regular',
      heading_text_color: '#333333',
      regular_text_color: '#333333',
      seo_title: '',
      seo_description: '',
      seo_keywords: '',
      fb_pixel_code: '',
      google_anal_resource_id: '',
      head_section_tracking_codes: '',
      after_opening_body_tag: '',
      before_closing_body_tag: '',
      isNewView: true,
      isNewLogo: true,
      isCustomLinks: true,
      isNewCourseSection: true,
      isNewBlueLines: true,
      isBrandNewLanding: true,
      dragAndDropLanding: true,
      isWithLinks: true,
   },
   landing: [
      {
         section: {
            slug: slug(),
            name: 'Header',
            props: {
               order: 0,
               duplicated: 'header',
               isWithLinksHeader: true,
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: '#272727',
               background_type: 'color',
               spacing: 'xs',
               backgroundLabel: 'Background Image (1900x80)',
               isBrandNewImg: true,
            },
         },
         components: [
            {
               slug: slug(),
               type: 'component',
               name: 'Three Column',
               props: { text: 'Component Props', isLogo: true },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'Image',
                     name: 'Image',
                     props: {
                        imgUrl: 'Your Logo',
                        text: '',
                        width: '200',
                        maxSize: '200',
                        radius: '0',
                        visibility: true,
                        isLogo: true,
                        imageLabel: 'Show Image (200x60)',
                        isBrandNewImg: true,
                     },
                  },
               ],
            },
            {
               slug: slug(),
               type: 'component',
               name: 'Links',
               props: { text: 'Component Props', isLink: true },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'LinkMi',
                     name: 'Link',
                     props: {
                        text: 'Courses',
                        bgColor: '#7cb740',
                        textColor: '#ffffff',
                        href: '',
                        disabled: true,
                        scroll_to: 'courses',
                        size: 'medium',
                        fontFamily: 'Inter-Bold',
                        fontStyle: 'bold',
                        textSize: 18,
                        allCaps: false,
                        visibility: true,
                        deleted: false,
                        target: '_blank',
                     },
                  },
               ],
            },
            {
               slug: slug(),
               type: 'component',
               name: 'Three Column',
               props: { text: 'Component Props', isLoginButton: true },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'ButtonMi',
                     name: 'Button Features',
                     props: {
                        text: 'Log In',
                        bgColor: '#7cb740',
                        textColor: '#ffffff',
                        href: '',
                        size: 'medium',
                        border: 'none',
                        blanked: true,
                        alignmentisOn: false,
                        allCaps: true,
                        fontFamily: 'Inter-Bold',
                        fontStyle: 'bold',
                        textSize: 19,
                        widthValue: 212,
                        isLoginButton: true,
                     },
                  },

               ],
            },
         ],
      },
      {
         section: {
            slug: slug(),
            name: 'Hero',
            props: {
               order: 1,
               duplicated: 1,
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: 'https://miestro-production.s3-us-west-2.amazonaws.com/landing/image.jpg',
               bgColor: '#ffffff',
               background_type: 'image',
               alignmentAvalaible: true,
               spacing: 'lg',
               alignment: 'center',
               backgroundLabel: 'Background Image (1900x600)',
               bgColorOverlay: '#ffffff',
               isBrandNewImg: true,
            },
         },
         components: [
            {
               slug: slug(),
               type: 'onecolumn',
               name: 'One Column',
               props: { text: 'Component Props' },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Title',
                     props: {
                        align: 'center',
                        text: '<span>Insert Product Headline Here</span>',
                        color: '#ffffff',
                        lineHeight: 11,
                        fontFamily: 'Inter-Black',
                        fontSize: 56,
                     },
                  },
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Text',
                     props: {
                        align: 'center',
                        text: '<span>Choose a background image without any text or distracting imagery. </span>',
                        color: '#ffffff',
                        lineHeight: 13,
                        fontFamily: 'Inter-Bold',
                        fontSize: 24,
                        paddingTop: 16,
                        paddingBottom: 16,
                        maxWidth: 450,
                        centerText: true,
                     },
                  },
                  {
                     slug: slug(),
                     type: 'ButtonMi',
                     name: 'Button Features',
                     props: {
                        text: 'Get Started',
                        bgColor: '#7cb740',
                        textColor: '#ffffff',
                        href: '',
                        size: 'medium',
                        widthChangeable: true,
                        border: 'none',
                        alignment: 'center',
                        fontFamily: 'Inter-Bold',
                        fontStyle: 'bold',
                        textSize: 19,
                        widthValue: 288,
                        allCaps: true,
                        marginTop: 30,
                        marginBottom: 30,
                        marginLeft: 0,
                        marginRight: 0,
                     },
                  },
               ],
            },
         ],
      },
      {
         section: {
            slug: slug(),
            name: 'What Will You Learn',
            props: {
               order: 2,
               duplicated: 2,
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: 'rgb(255,255,255)',
               background_type: 'image',
               spacing: 'lg',
               reverseAvailaible: true,
               reversed: false,
               bgColorOverlay: '#ffffff',
               paddingBottom: 50,
               paddingTop: 80,
               isBrandNewImg: true,
               backgroundLabel: 'Background Image (1900x760)',
            },
         },
         components: [
            {
               slug: slug(),
               type: 'component',
               name: 'Two Column',
               props: { text: 'Component Props' },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'Image',
                     name: 'Image',
                     props: {
                        imgUrl: 'https://miestro-production.s3-us-west-2.amazonaws.com/landing/mask.jpg',
                        width: '620',
                        radius: '0',
                        visibility: true,
                        imageLabel: 'Show Image (620x620)',
                        isBrandNewImg: true,
                     },
                  },
               ],
            },
            {
               slug: slug(),
               type: 'component',
               name: 'Two Column',
               props: { text: 'Component Props' },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Title',
                     props: {
                        align: 'left',
                        text: '<span>What Will You Learn</span>',
                        color: '#333333',
                        lineHeight: 11,
                        fontFamily: 'Inter-Black',
                        fontSize: 56,
                     },
                  },
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Text',
                     props: {
                        align: 'left',
                        text: '<span>Tell about the core of the class and upload an atmospherical photo to attract the attention of your students. Tell why your class is the best for learning. Tell about the core of the class and upload an atmospherical photo to attract the attention of your students. Tell why your class is the best for learning.</span>',
                        color: '#333333',
                        lineHeight: 15,
                        fontFamily: 'Inter-Regular',
                        fontSize: 16,
                        paddingTop: 16,
                        paddingBottom: 12,
                        maxWidth: 600,
                        centerText: false,
                     },
                  },
                  {
                     slug: slug(),
                     type: 'Bullet',
                     name: 'Bullet',
                     props: {
                        align: 'left',
                        isChecklist: true,
                        text1: 'Guidelines For Inkjet Cartridge Refill',
                        text2: 'Internet Advertising What Went Wrong',
                        text3: 'Advertising Relationships Vs Business Decisions',
                        text4: 'Stu Unger Rise And Fall Of A Poker Genius',
                        text5: 'Download Free Song For Ipod',
                        visibility1: true,
                        visibility2: true,
                        visibility3: true,
                        visibility4: true,
                        visibility5: true,
                        color: '#ffffff',
                        iconColor: '#ffffff',
                        borderColor: '#c6cbd4',
                        lineHeight: 15,
                        fontFamily: 'Inter-Medium',
                        fontSize: 16,
                        visibility: true,
                        iconType: 'circle',
                     },
                  },
                  {
                     slug: slug(),
                     type: 'ButtonMi',
                     name: 'Button Features',
                     props: {
                        text: 'Get Started',
                        bgColor: '#7cb740',
                        textColor: '#ffffff',
                        href: '',
                        size: 'medium',
                        widthChangeable: true,
                        border: 'none',
                        alignment: 'left',
                        fontFamily: 'Inter-Bold',
                        fontStyle: 'bold',
                        textSize: 19,
                        widthValue: 288,
                        allCaps: true,
                        marginTop: 0,
                        marginBottom: 0,
                        marginLeft: 0,
                        marginRight: 0,

                     },
                  },
               ],
            },
         ],
      },
      {
         section: {
            slug: slug(),
            name: 'Instructor',
            props: {
               order: 3,
               duplicated: 3,
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: 'rgb(255,255,255)',
               background_type: 'image',
               reverseAvailaible: true,
               reversed: false,
               spacing: 'lg',
               bgColorOverlay: '#ffffff',
               paddingBottom: 100,
               paddingTop: 50,
               paddingLeft: 15,
               paddingRight: 15,
               isBrandNewImg: true,
               backgroundLabel: 'Background Image (1900x760)',
            },
         },
         components: [
            {
               slug: slug(),
               type: 'component',
               name: 'Two Column',
               props: { text: 'Component Props', isType: 'instructorTexts'},
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Title',
                     props: {
                        align: 'left',
                        text: '<span>Carrie Hines</span>',
                        color: '#7cb740',
                        lineHeight: 10,
                        fontFamily: 'Inter-Bold',
                        fontSize: 16,
                        width: 100,
                        maxWidth: 556,
                     },
                  },
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Title',
                     props: {
                        align: 'left',
                        text: '<span>Your Instructor</span>',
                        color: '#333333',
                        lineHeight: 11,
                        fontFamily: 'Inter-Black',
                        fontSize: 56,
                        paddingBottom: 8,
                        paddingTop: 8,
                        width: 100,
                        maxWidth: 556,
                     },
                  },
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Text',
                     props: {
                        align: 'left',
                        text: '<span>“It’s always about timing. If it’s too soon, no one understands. If it’s too late, everyone’s forgotten.”</span>',
                        color: '#333333',
                        lineHeight: 13,
                        fontFamily: 'Palatino-BoldItalic',
                        fontSize: 24,
                        paddingBottom: 8,
                        paddingTop: 16,
                        width: 100,
                        maxWidth: 556,
                     },
                  },
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Text',
                     props: {
                        align: 'left',
                        text: '<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</span>',
                        color: '#333333',
                        lineHeight: 15,
                        fontFamily: 'Inter-Regular',
                        fontSize: 16,
                        paddingBottom: 16,
                        paddingTop: 8,
                        width: 100,
                        maxWidth: 556,
                     },
                  },
               ],

            },
            {
               slug: slug(),
               type: 'component',
               name: 'Two Column',
               props: { text: 'Component Props' },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'Image',
                     name: 'Image',
                     props: {
                        imgUrl: 'https://miestro-production.s3-us-west-2.amazonaws.com/landing/image.png',
                        width: '620',
                        radius: '0',
                        visibility: true,
                        imageLabel: 'Show Image (620x620)',
                        borderRadius: 1.5,
                        isBrandNewImg: true,
                     },
                  },
               ],

            },

         ],
      },

      {
         section: {
            slug: slug(),
            name: 'Featured Classes',
            props: {
               order: 5,
               duplicated: 4,
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: 'rgba(255, 255, 255, 0.99)',
               background_type: 'color',
               spacing: 'lg',
               bgColorOverlay: '#ffffff',
               paddingBottom: 100,
               paddingTop: 100,
               isBrandNewImg: true,
            },
         },
         components: [
            {
               slug: slug(),
               type: 'component',
               name: 'Three Column',
               props: { text: 'Component Props' },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Title',
                     props: {
                        align: 'center',
                        text: '<span>Featured Classes</span>',
                        color: '#333333',
                        lineHeight: 11,
                        fontFamily: 'Inter-Black',
                        fontSize: 48,
                     },
                  },
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Text',
                     props: {
                        align: 'center',
                        text: '<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</span>',
                        color: '#333333',
                        lineHeight: 15,
                        fontFamily: 'Inter-Regular',
                        fontSize: 16,
                        paddingTop: 16,
                        paddingBottom: 16,
                        maxWidth: 600,
                        width: 100,
                     },
                  },
               ],
            },
            {
               slug: slug(),
               type: 'component',
               name: 'Three Column',
               subcomponents: [],
               props: { text: 'Component Props', isNotDraggable: true, type: 'featured_classes' },
            },
            {
               slug: slug(),
               type: 'component',
               name: 'ThreeColumn',
               props: { text: 'Component Props' },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'ButtonMi',
                     name: 'Button Features',
                     props: {
                        text: 'Get Started',
                        bgColor: '#7cb740',
                        textColor: '#ffffff',
                        href: '',
                        size: 'medium',
                        widthChangeable: true,
                        border: 'none',
                        blanked: true,
                        alignment: 'center',
                        fontFamily: 'Inter-Bold',
                        fontStyle: 'bold',
                        textSize: 19,
                        widthValue: 288,
                        allCaps: true,
                        marginTop: 20,
                        marginBottom: 20,
                        marginLeft: 0,
                        marginRight: 0,
                     },
                  },
               ],
            },
         ],
      },
      {
         section: {
            slug: slug(),
            name: 'Pricing',
            props: {
               order: 6,
               duplicated: 'pricing',
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: '#272727',
               background_type: 'image',
               imageOverlay: false,
               spacing: 'sm',
               backgroundLabel: 'Background Image (1900x400)',
               bgColorOverlay: '#272727',
               isBrandNewImg: true,
            },
         },
         components: [
            {
               slug: slug(),
               type: 'component',
               name: 'Three Column',
               props: { text: 'Component Props' },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Title',
                     props: {
                        align: 'center',
                        text: '<span>Ready To Get Started?</span>',
                        color: '#ffffff',
                        lineHeight: 11,
                        fontFamily: 'Inter-Bold',
                        fontSize: 56,
                     },
                  },
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Text',
                     props: {
                        align: 'center',
                        text: '<span>Join countless coaches, consultants, teachers and experts who are creating their own online memberships!</span>',
                        color: '#ffffff',
                        lineHeight: 15,
                        fontFamily: 'Inter-Bold',
                        fontSize: 16,
                        maxWidth: 458,
                        width: 100,
                        centerText: true,
                        paddingTop: 25,
                        paddingBottom: 25,
                        paddingLeft: 0,
                        paddingRight: 0,
                     },
                  },
               ],

            },
            {
               slug: slug(),
               type: 'component',
               name: 'Three Column',
               props: { text: 'Component Props', isNotDraggable: true, type: 'pricing' },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'Pricing',
                     name: 'Pricing',
                     props: {
                        text: 'Montly Fee Title Here',
                        price: '$99/m',
                        textColor: '#ffffff',
                        textColor_selected: '#ffffff',
                        bgColor: '#333333',
                        bgColor_selected: '#333333',
                        border_selected: 'solid 2px #7cb740',
                        border: 'solid 2px #333333',
                        newcolor: 'pricing_color',
                     },
                  },
               ],
            },
            {
               slug: slug(),
               type: 'component',
               name: 'Pricing Button',
               props: { text: 'Component Props', pricingButton: true },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'ButtonMi',
                     name: 'Button Features',
                     props: {
                        text: 'Get Started',
                        bgColor: '#7cb740',
                        textColor: '#ffffff',
                        href: '',
                        size: 'medium',
                        widthChangeable: true,
                        border: 'none',
                        blanked: true,
                        scroll_to_section: true,
                        pricing_button: true,
                        alignment: 'center',
                        fontFamily: 'Inter-Bold',
                        fontStyle: 'bold',
                        textSize: 19,
                        widthValue: 288,
                        allCaps: true,
                        marginTop: 20,
                        marginBottom: 20,
                        marginLeft: 0,
                        marginRight: 0,
                     },
                  },
               ],
            },
         ],
      },
      {
         section: {
            slug: slug(),
            name: 'Footer',
            props: {
               order: 7,
               duplicated: 'footer',
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: '#272727',
               background_type: 'color',
               spacing: 'sm',
               bgColorOverlay: '#272727',
               isBrandNewImg: true,
            },
         },
         components: [
            {
               slug: slug(),
               type: 'component',
               name: 'One Column',
               props: { text: 'footer' },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'ButtonMi',
                     name: 'Button Features',
                     props: {
                        text: 'Privacy Policy',
                        bgColor: '#272727',
                        textColor: '#ffffff',
                        size: 'extsmall',
                        linked: true,
                        blanked: false,
                        href: '',
                        border: 'none',
                        textSize: 16,
                        borderRadius: 0,
                        fontFamily: 'Inter-Regular',
                        isPrivacy: true,
                     },
                  },
                  {
                     slug: slug(),
                     type: 'ButtonMi',
                     name: 'Button Features',
                     props: {
                        text: 'Terms',
                        bgColor: '#272727',
                        textColor: '#ffffff',
                        size: 'extsmall',
                        linked: true,
                        blanked: false,
                        href: '',
                        border: 'none',
                        textSize: 16,
                        borderRadius: 0,
                        fontFamily: 'Inter-Regular',
                        isTerms: true,
                     },
                  },
                  {
                     slug: slug(),
                     type: 'ButtonMi',
                     name: 'Button Features',
                     props: {
                        text: 'Copyright © 2023 by Personal Life Coach.',
                        bgColor: '#272727',
                        textColor: '#ffffff',
                        size: 'extsmall',
                        linked: true,
                        blanked: false,
                        href: '',
                        border: 'none',
                        textSize: 16,
                        borderRadius: 0,
                        fontFamily: 'Inter-Regular',
                        alignmentisOn: false,
                        isCopyright: true,
                     },
                  },
               ],
            },

         ],
      },
      {
         section: {
            slug: slug(),
            name: 'Lessons area',
            props: {
               order: 4,
               duplicated: 'course',
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: '#272727',
               background_type: 'color',
               spacing: 'md',
               videoAvailaible: false,
               bgColorOverlay: '#ffffff',
               isBrandNewImg: true,
            },
         },
         components: [
            {
               slug: slug(),
               type: 'component',
               name: 'Three Column',
               props: { text: 'Component Props' },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'Text',
                     name: 'Title',
                     props: {
                        align: 'center',
                        text: '<span>Class Curriculum</span>',
                        color: '#ffffff',
                        lineHeight: 10,
                        fontFamily: 'Inter-Black',
                        fontSize: 48,
                     },
                  },
               ],
            },
            {
               slug: slug(),
               type: 'component',
               name: 'Three Column',
               props: { text: 'Component Props', isNotDraggable: true, type: 'classes_conteiner' },
               subcomponents: [
                  {
                     slug: slug(),
                     type: 'Text',
                     name: "Curriculum's Colors",
                     props: {
                        text: "<span>Curriculum's Colors</span>",
                        visibility: true,
                        label: "Curriculum's Colors",
                        lessonsBgColor: '#333333',
                        lessonsColor: '#ffffff',
                        isLessonsBgColor: true,
                        lineHeight: 18,
                        fontFamily: 'Inter-Medium',
                        fontSize: 18,
                     },
                  },
               ],
            },
            {
               slug: slug(),
               type: 'component',
               name: 'Three Column',
               props: { text: 'Component Props' },
               subcomponents: [],
            },
         ],
      },
   ],
};

export default state;
