/* eslint-disable global-require */
const slug = () => {
   function s4() {
      return new Date().getTime() + Math.floor(Math.random() * 1000000);
   }
   return `miestro-${ s4() }`;
};

const state = {
   landing_name: 'landing_13',
   landing_metas: {
      landing_favicon: 'https://miestro-production.s3-us-west-2.amazonaws.com/landing/favico.ico',
      heading_font: 'Inter-Black',
      regular_font: 'Inter-Regular',
      heading_text_color: '#333333',
      regular_text_color: '#333333',
      seo_title: '',
      seo_description: '',
      seo_keywords: '',
      fb_pixel_code: '',
      google_anal_resource_id: '',
      head_section_tracking_codes: '',
      after_opening_body_tag: '',
      before_closing_body_tag: '',
      isNewView: true,
      isNewLogo: true,
      isCustomLinks: true,
      isNewCourseSection: true,
      isNewBlueLines: true,
      isBrandNewLanding: true,
      dradAndDropLanding: true,
   },
   landing: [
      {
         section: {
            // slug unique identifier
            slug: slug(),
            // component name (used as show name for sidebar)
            name: 'Header',
            // section_props
            props: {
               // props:value
               order: 0,
               duplicated: 'header',
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: '#272727',
               background_type: 'color',
               spacing: 'xs',
               backgroundLabel: 'Background Image (1900x80)',
               isBrandNewImg: true,
            },
         },
         components: [
            {
               slug: slug(),
               type: 'Image',
               name: 'Image',
               props: {
                  imgUrl: 'Your Logo',
                  text: '',
                  width: '200',
                  maxSize: '200',
                  radius: '0',
                  visibility: true,
                  isLogo: true,
                  imageLabel: 'Show Image (200x60)',
                  isBrandNewImg: true,
               },
            },
            {
               slug: slug(),
               type: 'ButtonMi',
               name: 'Button Features',
               props: {
                  text: 'Log In',
                  bgColor: '#7cb740',
                  textColor: '#ffffff',
                  href: '',
                  size: 'medium',
                  border: 'none',
                  blanked: true,
                  alignmentisOn: false,
                  allCaps: true,
                  fontFamily: 'Inter-Bold',
                  fontStyle: 'bold',
                  textSize: 19,
                  widthValue: 212,
                  isLoginButton: true,
               },
            },

         ],
      },
      {
         section: {
            // slug unique identifier
            slug: slug(),
            // component name (used as show name for sidebar)
            name: 'Hero',
            // section_props
            props: {
               // props:value
               order: 1,
               duplicated: 1,
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: 'https://miestro-production.s3-us-west-2.amazonaws.com/landing/image.jpg',
               bgColor: '#ffffff',
               background_type: 'image',
               alignmentAvalaible: true,
               spacing: 'lg',
               alignment: 'center',
               backgroundLabel: 'Background Image (1900x600)',
               bgColorOverlay: '#ffffff',
               isBrandNewImg: true,
            },
         },
         components: [
            {
               slug: slug(),
               type: 'Text',
               name: 'Title',
               props: {
                  align: 'center',
                  text: '<span>Insert Product Headline Here</span>',
                  color: '#ffffff',
                  lineHeight: 11,
                  fontFamily: 'Inter-Black',
                  fontSize: 56,
               },
            },
            {
               slug: slug(),
               type: 'Text',
               name: 'Text',
               props: {
                  align: 'center',
                  text: '<span>Choose a background image without any text or distracting imagery. </span>',
                  color: '#ffffff',
                  lineHeight: 13,
                  fontFamily: 'Inter-Bold',
                  fontSize: 24,
                  paddingTop: 16,
                  paddingBottom: 16,
               },
            },
            {
               slug: slug(),
               type: 'ButtonMi',
               name: 'Button Features',
               props: {
                  text: 'Get Started',
                  bgColor: '#7cb740',
                  textColor: '#ffffff',
                  href: '',
                  size: 'medium',
                  widthChangeable: true,
                  border: 'none',
                  alignment: 'center',
                  fontFamily: 'Inter-Bold',
                  fontStyle: 'bold',
                  textSize: 19,
                  widthValue: 288,
                  allCaps: true,
               },
            },
         ],
      },
      {
         section: {
            slug: slug(),
            name: 'What Will You Learn',
            props: {
               order: 2,
               duplicated: 2,
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: 'rgb(255,255,255)',
               background_type: 'image',
               spacing: 'lg',
               reverseAvailaible: true,
               reversed: false,
               bgColorOverlay: '#ffffff',
               paddingBottom: 50,
               paddingTop: 80,
               isBrandNewImg: true,
               backgroundLabel: 'Background Image (1900x760)',
            },
         },
         components: [
            {
               slug: slug(),
               type: 'Image',
               name: 'Image',
               props: {
                  imgUrl: 'https://miestro-production.s3-us-west-2.amazonaws.com/landing/mask.jpg',
                  width: '620',
                  radius: '0',
                  visibility: true,
                  imageLabel: 'Show Image (620x620)',
                  isBrandNewImg: true,
               },
            },
            {
               slug: slug(),
               type: 'Text',
               name: 'Title',
               props: {
                  align: 'left',
                  text: '<span>What Will You Learn</span>',
                  color: '#333333',
                  lineHeight: 11,
                  fontFamily: 'Inter-Black',
                  fontSize: 56,
               },
            },
            {
               slug: slug(),
               type: 'Text',
               name: 'Text',
               props: {
                  align: 'left',
                  text: '<span>Tell about the core of the class and upload an atmospherical photo to attract the attention of your students. Tell why your class is the best for learning. Tell about the core of the class and upload an atmospherical photo to attract the attention of your students. Tell why your class is the best for learning.</span>',
                  color: '#333333',
                  lineHeight: 15,
                  fontFamily: 'Inter-Regular',
                  fontSize: 16,
                  paddingTop: 16,
                  paddingBottom: 12,
               },
            },
            {
               slug: slug(),
               type: 'Text',
               name: 'Text',
               props: {
                  align: 'left',
                  isChecklist: true,
                  text1: 'Guidelines For Inkjet Cartridge Refill',
                  text2: 'Internet Advertising What Went Wrong',
                  text3: 'Advertising Relationships Vs Business Decisions',
                  text4: 'Stu Unger Rise And Fall Of A Poker Genius',
                  text5: 'Download Free Song For Ipod',
                  visibility1: true,
                  visibility2: true,
                  visibility3: true,
                  visibility4: true,
                  visibility5: true,
                  color: '#333333',
                  iconColor: '#7CB740',
                  borderColor: '#c6cbd4',
                  lineHeight: 15,
                  fontFamily: 'Inter-Medium',
                  fontSize: 16,
                  visibility: true,
               },
            },
            {
               slug: slug(),
               type: 'ButtonMi',
               name: 'Button Features',
               props: {
                  text: 'Get Started',
                  bgColor: '#7cb740',
                  textColor: '#ffffff',
                  href: '',
                  size: 'medium',
                  widthChangeable: true,
                  border: 'none',
                  alignment: 'left',
                  fontFamily: 'Inter-Bold',
                  fontStyle: 'bold',
                  textSize: 19,
                  widthValue: 288,
                  allCaps: true,

               },
            },
         ],
      },
      {
         section: {
            slug: slug(),
            name: 'Instructor',
            props: {
               order: 3,
               duplicated: 3,
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: 'rgb(255,255,255)',
               background_type: 'image',
               reverseAvailaible: true,
               reversed: false,
               spacing: 'lg',
               bgColorOverlay: '#ffffff',
               paddingBottom: 100,
               paddingTop: 50,
               paddingLeft: 15,
               paddingRight: 15,
               isBrandNewImg: true,
               backgroundLabel: 'Background Image (1900x760)',
            },
         },
         components: [
            {
               slug: slug(),
               type: 'Image',
               name: 'Image',
               props: {
                  imgUrl: 'https://miestro-production.s3-us-west-2.amazonaws.com/landing/image.png',
                  width: '620',
                  radius: '0',
                  visibility: true,
                  imageLabel: 'Show Image (620x620)',
                  borderRadius: 1.5,
                  isBrandNewImg: true,
               },
            },
            {
               slug: slug(),
               type: 'Text',
               name: 'Title',
               props: {
                  align: 'left',
                  text: '<span>Your Instructor</span>',
                  color: '#333333',
                  lineHeight: 11,
                  fontFamily: 'Inter-Black',
                  fontSize: 56,
                  paddingBottom: 8,
                  paddingTop: 8,
               },
            },
            {
               slug: slug(),
               type: 'Text',
               name: 'Text',
               props: {
                  align: 'left',
                  text: '<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</span>',
                  color: '#333333',
                  lineHeight: 15,
                  fontFamily: 'Inter-Regular',
                  fontSize: 16,
                  paddingBottom: 16,
                  paddingTop: 8,
               },
            },
            {
               slug: slug(),
               type: 'Text',
               name: 'Title',
               props: {
                  align: 'left',
                  text: '<span>Carrie Hines</span>',
                  color: '#7cb740',
                  lineHeight: 10,
                  fontFamily: 'Inter-Bold',
                  fontSize: 16,
               },
            },
            {
               slug: slug(),
               type: 'Text',
               name: 'Text',
               props: {
                  align: 'left',
                  text: '<span>“It’s always about timing. If it’s too soon, no one understands. If it’s too late, everyone’s forgotten.”</span>',
                  color: '#333333',
                  lineHeight: 13,
                  fontFamily: 'Palatino-BoldItalic',
                  fontSize: 24,
                  paddingBottom: 8,
                  paddingTop: 16,
               },
            },
         ],
      },
      //  FEATURES SECTIONS DEFAULT JSON
      {
         section: {
            // slug unique identifier
            slug: slug(),
            // component name (used as show name for sidebar)
            name: 'Featured Classes',
            // section_props
            props: {
               // props:value
               order: 5,
               duplicated: 4,
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: 'rgba(255, 255, 255, 0.99)',
               background_type: 'color',
               spacing: 'lg',
               bgColorOverlay: '#ffffff',
               paddingBottom: 100,
               paddingTop: 100,
               isBrandNewImg: true,
            },
         },
         components: [
            {
               slug: slug(),
               type: 'Text',
               name: 'Title',
               props: {
                  align: 'center',
                  text: '<span>Featured Classes</span>',
                  color: '#333333',
                  lineHeight: 11,
                  fontFamily: 'Inter-Black',
                  fontSize: 48,
               },
            },
            {
               slug: slug(),
               type: 'Text',
               name: 'Text',
               props: {
                  align: 'center',
                  text: '<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</span>',
                  color: '#333333',
                  lineHeight: 15,
                  fontFamily: 'Inter-Regular',
                  fontSize: 16,
                  paddingTop: 16,
                  paddingBottom: 16,
               },
            },
            {
               slug: slug(),
               type: 'ButtonMi',
               name: 'Button Features',
               props: {
                  text: 'Get Started',
                  bgColor: '#7cb740',
                  textColor: '#ffffff',
                  href: '',
                  size: 'medium',
                  widthChangeable: true,
                  border: 'none',
                  blanked: true,
                  alignment: 'center',
                  fontFamily: 'Inter-Bold',
                  fontStyle: 'bold',
                  textSize: 19,
                  widthValue: 288,
                  allCaps: true,
               },
            },
         ],
      },
      {
         section: {
            slug: slug(),
            name: 'Pricing',
            props: {
               order: 6,
               duplicated: 'pricing',
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: '#272727',
               background_type: 'image',
               imageOverlay: false,
               spacing: 'sm',
               backgroundLabel: 'Background Image (1900x400)',
               bgColorOverlay: '#272727',
               isBrandNewImg: true,
            },
         },
         components: [
            {
               slug: slug(),
               type: 'Text',
               name: 'Title',
               props: {
                  align: 'center',
                  text: '<span>Ready To Get Started?</span>',
                  color: '#ffffff',
                  lineHeight: 11,
                  fontFamily: 'Inter-Bold',
                  fontSize: 56,
               },
            },
            {
               slug: slug(),
               type: 'Text',
               name: 'Text',
               props: {
                  align: 'center',
                  text: '<span>Join countless coaches, consultants, teachers and experts who are creating their own online memberships!</span>',
                  color: '#ffffff',
                  lineHeight: 15,
                  fontFamily: 'Inter-Bold',
                  fontSize: 16,
               },
            },
            {
               slug: slug(),
               type: 'Pricing',
               name: 'Pricing',
               props: {
                  text: 'Montly Fee Title Here',
                  price: '$99/m',
                  textColor: '#ffffff',
                  textColor_selected: '#ffffff',
                  bgColor: '#333333',
                  bgColor_selected: '#333333',
                  border_selected: 'solid 2px #7cb740',
                  border: 'solid 2px #333333',
                  newcolor: 'pricing_color',
               },
            },
            {
               slug: slug(),
               type: 'ButtonMi',
               name: 'Button Features',
               props: {
                  text: 'Get Started',
                  bgColor: '#7cb740',
                  textColor: '#ffffff',
                  href: '',
                  size: 'medium',
                  widthChangeable: true,
                  border: 'none',
                  blanked: true,
                  scroll_to_section: true,
                  pricing_button: true,
                  alignment: 'center',
                  fontFamily: 'Inter-Bold',
                  fontStyle: 'bold',
                  textSize: 19,
                  widthValue: 288,
                  allCaps: true,
               },
            },
         ],
      },
      {
         section: {
            // slug unique identifier
            slug: slug(),
            // component name (used as show name for sidebar)
            name: 'Footer',
            // section_props
            props: {
               // props:value
               order: 7,
               duplicated: 'footer',
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: '#272727',
               background_type: 'color',
               spacing: 'sm',
               bgColorOverlay: '#272727',
               isBrandNewImg: true,
            },
         },
         components: [
            {
               slug: slug(),
               type: 'ButtonMi',
               name: 'Button Features',
               props: {
                  text: 'Privacy Policy',
                  bgColor: '#272727',
                  textColor: '#ffffff',
                  size: 'extsmall',
                  linked: true,
                  blanked: false,
                  href: '',
                  border: 'none',
                  textSize: 16,
                  borderRadius: 0,
                  fontFamily: 'Inter-Regular',
               },
            },
            {
               slug: slug(),
               type: 'ButtonMi',
               name: 'Button Features',
               props: {
                  text: 'Terms',
                  bgColor: '#272727',
                  textColor: '#ffffff',
                  size: 'extsmall',
                  linked: true,
                  blanked: false,
                  href: '',
                  border: 'none',
                  textSize: 16,
                  borderRadius: 0,
                  fontFamily: 'Inter-Regular',
               },
            },
            {
               slug: slug(),
               type: 'ButtonMi',
               name: 'Button Features',
               props: {
                  text: 'Copyright © 2023 by Personal Life Coach.',
                  bgColor: '#272727',
                  textColor: '#ffffff',
                  size: 'extsmall',
                  linked: true,
                  blanked: false,
                  href: '',
                  border: 'none',
                  textSize: 16,
                  borderRadius: 0,
                  fontFamily: 'Inter-Regular',
                  alignmentisOn: false,
                  isCopyright: true,
               },
            },
         ],
      },
      {
         section: {
            slug: slug(),
            name: 'Lessons area',
            props: {
               order: 4,
               duplicated: 'course',
               visibility: true,
               bgVideoSrc: '',
               bgImgSrc: '',
               bgColor: '#272727',
               background_type: 'color',
               spacing: 'md',
               videoAvailaible: false,
               bgColorOverlay: '#ffffff',
               isBrandNewImg: true,
            },
         },
         components: [
            {
               slug: slug(),
               type: 'Text',
               name: "Curriculum's Colors",
               props: {
                  text: "<span>Curriculum's Colors</span>",
                  visibility: true,
                  label: "Curriculum's Colors",
                  lessonsBgColor: '#333333',
                  lessonsColor: '#ffffff',
                  isLessonsBgColor: true,
                  lineHeight: 18,
                  fontFamily: 'Inter-Medium',
                  fontSize: 18,
               },
            },
            {
               slug: slug(),
               type: 'Text',
               name: 'Title',
               props: {
                  align: 'center',
                  text: '<span>Class Curriculum</span>',
                  color: '#ffffff',
                  lineHeight: 10,
                  fontFamily: 'Inter-Black',
                  fontSize: 48,
               },
            },
         ],
      },
   ],
};

export default state;
