// AI Chatbot Action Types

// Settings
export const GET_AI_CHATBOT_SETTINGS_START = 'GET_AI_CHATBOT_SETTINGS_START';
export const GET_AI_CHATBOT_SETTINGS_COMPLETED = 'GET_AI_CHATBOT_SETTINGS_COMPLETED';
export const GET_AI_CHATBOT_SETTINGS_FAILED = 'GET_AI_CHATBOT_SETTINGS_FAILED';

export const UPDATE_AI_CHATBOT_SETTINGS_START = 'UPDATE_AI_CHATBOT_SETTINGS_START';
export const UPDATE_AI_CHATBOT_SETTINGS_COMPLETED = 'UPDATE_AI_CHATBOT_SETTINGS_COMPLETED';
export const UPDATE_AI_CHATBOT_SETTINGS_FAILED = 'UPDATE_AI_CHATBOT_SETTINGS_FAILED';

// Widget State
export const TOGGLE_AI_CHATBOT_WIDGET = 'TOGGLE_AI_CHATBOT_WIDGET';
export const SET_AI_CHATBOT_CONTEXT = 'SET_AI_CHATBOT_CONTEXT';
export const ADD_AI_CHATBOT_MESSAGE = 'ADD_AI_CHATBOT_MESSAGE';
export const CLEAR_AI_CHATBOT_MESSAGES = 'CLEAR_AI_CHATBOT_MESSAGES';

// Conversations
export const GET_AI_CHATBOT_CONVERSATIONS_START = 'GET_AI_CHATBOT_CONVERSATIONS_START';
export const GET_AI_CHATBOT_CONVERSATIONS_COMPLETED = 'GET_AI_CHATBOT_CONVERSATIONS_COMPLETED';
export const GET_AI_CHATBOT_CONVERSATIONS_FAILED = 'GET_AI_CHATBOT_CONVERSATIONS_FAILED';

// Analytics
export const GET_AI_CHATBOT_ANALYTICS_START = 'GET_AI_CHATBOT_ANALYTICS_START';
export const GET_AI_CHATBOT_ANALYTICS_COMPLETED = 'GET_AI_CHATBOT_ANALYTICS_COMPLETED';
export const GET_AI_CHATBOT_ANALYTICS_FAILED = 'GET_AI_CHATBOT_ANALYTICS_FAILED';
