export const GET_PLANS_START = 'plans/GET_PLANS_START';
export const GET_PLANS_COMPLETED = 'plans/GET_PLANS_COMPLETED';
export const GET_PLANS_FAILED = 'plans/GET_PLANS_FAILED';

export const CONNECT_PLAN = 'plans/CONNECT_PLAN';
export const CANCEL_PLAN = 'plans/CANCEL_PLAN';
export const SET_PLANS_MODAL_STATE = 'plans/SET_PLANS_MODAL_STATE';
export const SET_CARD_MODAL_STATE = 'plans/SET_CARD_MODAL_STATE';
export const SET_PLANS_MODAL_STATE_START = 'plans/SET_PLANS_MODAL_STATE_START';
export const SET_PLANS_MODAL_STATE_FAILED = 'plans/SET_PLANS_MODAL_STATE_FAILED';
export const SET_CARD_UPTAE_MODAL_STATE = 'plans/SET_CARD_UPTAE_MODAL_STATE';
