export const exampleSections = [
   {
      'school_room_section': {
         'id': 15,
         'name': 'Main Background',
         'slug': 'miestro-1672120701BAOVNMkv5Si3n5VU93ghOjeNYVn6DGn6',
         'school_room_landing_id': 3,
         'props': {
            'bgColor': '#ffffff',
            'bgImgSrc': null,
            'duplicated': 'main_background',
            'background_type': 'color',
         },
         'created_at': '2022-12-27T05:58:21.000000Z',
         'updated_at': '2023-02-09T07:59:03.000000Z',
         'school_room_components': [],
      },
      'school_room_components': [],
   },
   {
      'school_room_section': {
         'id': 16,
         'name': 'Header',
         'slug': 'miestro-1672120701Z2zJG3xgslaaDs4OtJ1xQW77IuekhHWK',
         'school_room_landing_id': 3,
         'props': {
            'color': '#ffffff',
            'bgColor': '#272727',
            'bgImgSrc': null,
            'duplicated': 'header',
            'templateType': 'template3',
            'background_type': 'color',
         },
         'created_at': '2022-12-27T05:58:21.000000Z',
         'updated_at': '2023-02-09T07:59:03.000000Z',
         'school_room_components': [],
      },
      'school_room_components': [],
   },
   {
      'school_room_section': {
         'id': 17,
         'name': 'Hero',
         'slug': 'miestro-1672120701rOXE6vNUkxBrHcYaqrdohdYguMYZpOHe',
         'school_room_landing_id': 3,
         'props': {
            'bgColor': 'transparent',
            'opacity': '0.5',
            'bgImgSrc': null,
            'duplicated': 'hero',
            'templateType': 'template3',
            'opacity_color': '#03111e',
            'background_type': 'color',
            'school_slider_status': true,
            'school_header_opacity': true,
         },
         'created_at': '2022-12-27T05:58:21.000000Z',
         'updated_at': '2023-02-09T07:59:03.000000Z',
         'school_room_components': [
            {
               'id': 21,
               'name': 'Banner',
               'type': 'banner',
               'slug': 'miestro-1672120701NFsB3Qm41cygUvJHGWAYnOEzY5sSIAxo',
               'props': {
                  'order': 0,
                  'school_banner_src': null,
                  'school_show_banner': false,
               },
               'school_room_section_id': 17,
               'subcomponent': [
                  {
                     'slug': 'miestro-1672120701GjSSUptuBhjSbhyghjJBUHNwoHY1S4iH',
                     'type': 'banner_title',
                     'name': 'Title',
                     'props': {
                        'text': null,
                        'visibility': true,
                        'isBanner': true,
                        'disabled': true,
                        'paddingBottom': '1',
                        'paddingLeft': '9',
                        'justifyContent': 'flex-end',
                        'alignItems': 'flex-start',
                     },
                  },
               ],
               'created_at': '2022-12-27T05:58:21.000000Z',
               'updated_at': '2023-02-09T07:59:03.000000Z',
            },
            {
               'id': 22,
               'name': 'Slider',
               'type': 'slider',
               'slug': 'miestro-1672120701J0pVZaCKD7s7xr9bqgOBLVHXDfAmmu6T',
               'props': {
                  'order': 1,
                  'visibility': true,
                  'school_class_type': 'slider',
               },
               'school_room_section_id': 17,
               'subcomponent': [
                  {
                     'slug': 'miestro-1675930096022-undefined',
                     'type': 'class',
                     'name': 'Class',
                     'props': {
                        'order': 0,
                        'picture_src': 'https://miestro-local.s3-us-west-2.amazonaws.com/bd51e1a9098f4898f6cfab183c8e1499/jecej3edh_1675929532426.png',
                        'course_id': 7,
                        'availableDelete': true,
                        'paddingBottom': '1',
                        'paddingLeft': '9',
                        'justifyContent': 'flex-end',
                        'alignItems': 'flex-start',
                        'classType': 'slider',
                     },
                     'subcomponent': [
                        {
                           'slug': 'miestro-1675930506814-1',
                           'type': 'slider_title',
                           'name': 'Class Name',
                           'props': {
                              'visibility': true,
                              'hasVisibility': true,
                              'color': '#ffffff',
                              'fontSize': '56',
                              'fontFamily': 'Avenir Next',
                           },
                        },
                        {
                           'slug': 'miestro-1675930516916-2',
                           'type': 'slider_description',
                           'name': 'Class Description',
                           'props': {
                              'visibility': true,
                              'hasVisibility': true,
                              'color': '#FFFFFF',
                              'fontSize': '18',
                              'fontFamily': 'Avenir Next',
                           },
                        },
                        {
                           'slug': 'miestro-1675930090850-3',
                           'type': 'slider_author',
                           'name': 'Class Author',
                           'props': {
                              'visibility': true,
                              'hasVisibility': true,
                              'color': '#ffffff',
                              'color_bio': '#ffffff',
                              'fontSize': '16',
                              'fontSize_bio': '12',
                              'fontFamily': 'Avenir Next DemiBold',
                              'fontFamily_bio': 'Avenir Next Regular',
                           },
                        },
                        {
                           'slug': 'miestro-1675930461151-4',
                           'type': 'slider_button',
                           'name': 'Class Button',
                           'props': {
                              'visibility': true,
                              'hasVisibility': true,
                              'color': '#FFFFFF',
                              'fontSize': '14',
                              'fontFamily': 'Avenir Next',
                              'width': '239',
                           },
                        },
                     ],
                     'course': {
                        'id': 7,
                        'paypal_product_id': null,
                        'paypal_id': null,
                        'community_id': null,
                        'programm_id': null,
                        'active_landing_url': null,
                        'checkout_landing_id': 0,
                        'name': 'new course 0',
                        'subtitle': null,
                        'is_published': 1,
                        'drip_days': null,
                        'drip_date': null,
                        'publishing_date': '',
                        'drip_type': null,
                        'show_course': 1,
                        'is_duplicated': 1,
                        'duplicate_count': 1,
                        'original_id': 1,
                        'duplication_in_process': 0,
                        'description': '',
                        'author': null,
                        'picture_src': 'http://miestro.loc/images/defaults/thumbnail.png',
                        'thumbnail_image': 'http://miestro.loc/images/defaults/thumbnail.png',
                        'logo': 'http://miestro.loc/images/defaults/course-logo.png',
                        'url': 'new-course10',
                        'landing_url': null,
                        'landing_custom_url': null,
                        'is_custom_url': 0,
                        'bio_description': null,
                        'seo_title': null,
                        'seo_description': null,
                        'seo_image': null,
                        'seo_keywords': null,
                        'landing_page_id': null,
                        'finish_message': null,
                        'show_intro': 0,
                        'intro_video': null,
                        'thank_you_page': 3,
                        'thank_you_page_url': null,
                        'thank_you_title': null,
                        'thank_you_message': null,
                        'thank_you_video_type': null,
                        'thank_you_video_url': null,
                        'thank_you_video_original_url': null,
                        'thank_you_video_width': null,
                        'thank_you_title_show': 0,
                        'thank_you_message_show': 0,
                        'thank_you_video_show': 0,
                        'thank_you_button_text_color': '#fff',
                        'thank_you_button_bg_color': '#3f4f65',
                        'thank_you_button_text': 'Continue',
                        'thank_you_page_active': 1,
                        'thank_you_button_font_size': null,
                        'is_rated_on': 0,
                        'rated_ids': null,
                        'created_at': '2023-02-09T07:56:47.000000Z',
                        'updated_at': '2023-02-09T11:58:25.000000Z',
                        'type': '0',
                        'rated_courses': [],
                        'sections': [],
                        'lessons': [],
                        'authors': [],
                     },
                  },
                  {
                     'slug': 'miestro-1675929650242-undefined',
                     'type': 'class',
                     'name': 'Class',
                     'props': {
                        'order': 0,
                        'picture_src': 'https://miestro-local.s3-us-west-2.amazonaws.com/bd51e1a9098f4898f6cfab183c8e1499/35ie690g7_1675929527991.png',
                        'course_id': 1,
                        'availableDelete': true,
                        'paddingBottom': '1',
                        'paddingLeft': '9',
                        'justifyContent': 'flex-end',
                        'alignItems': 'flex-start',
                        'classType': 'slider',
                     },
                     'subcomponent': [
                        {
                           'slug': 'miestro-1675930072584-1',
                           'type': 'slider_title',
                           'name': 'Class Name',
                           'props': {
                              'visibility': true,
                              'hasVisibility': true,
                              'color': '#ffffff',
                              'fontSize': '56',
                              'fontFamily': 'Avenir Next',
                           },
                        },
                        {
                           'slug': 'miestro-1675929916378-2',
                           'type': 'slider_description',
                           'name': 'Class Description',
                           'props': {
                              'visibility': true,
                              'hasVisibility': true,
                              'color': '#FFFFFF',
                              'fontSize': '18',
                              'fontFamily': 'Avenir Next',
                           },
                        },
                        {
                           'slug': 'miestro-1675929996682-3',
                           'type': 'slider_author',
                           'name': 'Class Author',
                           'props': {
                              'visibility': true,
                              'hasVisibility': true,
                              'color': '#ffffff',
                              'color_bio': '#ffffff',
                              'fontSize': '16',
                              'fontSize_bio': '12',
                              'fontFamily': 'Avenir Next DemiBold',
                              'fontFamily_bio': 'Avenir Next Regular',
                           },
                        },
                        {
                           'slug': 'miestro-1675929931669-4',
                           'type': 'slider_button',
                           'name': 'Class Button',
                           'props': {
                              'visibility': true,
                              'hasVisibility': true,
                              'color': '#FFFFFF',
                              'fontSize': '14',
                              'fontFamily': 'Avenir Next',
                              'width': '239',
                           },
                        },
                     ],
                     'course': {
                        'id': 1,
                        'paypal_product_id': null,
                        'paypal_id': null,
                        'community_id': null,
                        'programm_id': null,
                        'active_landing_url': null,
                        'checkout_landing_id': 0,
                        'name': 'new course',
                        'subtitle': null,
                        'is_published': 1,
                        'drip_days': null,
                        'drip_date': null,
                        'publishing_date': '',
                        'drip_type': null,
                        'show_course': 1,
                        'is_duplicated': 0,
                        'duplicate_count': 1,
                        'original_id': null,
                        'duplication_in_process': 0,
                        'description': '',
                        'author': null,
                        'picture_src': 'http://miestro.loc/images/defaults/thumbnail.png',
                        'thumbnail_image': 'http://miestro.loc/images/defaults/thumbnail.png',
                        'logo': 'http://miestro.loc/images/defaults/course-logo.png',
                        'url': 'new-course1',
                        'landing_url': null,
                        'landing_custom_url': null,
                        'is_custom_url': 0,
                        'bio_description': null,
                        'seo_title': null,
                        'seo_description': null,
                        'seo_image': null,
                        'seo_keywords': null,
                        'landing_page_id': null,
                        'finish_message': null,
                        'show_intro': 0,
                        'intro_video': null,
                        'thank_you_page': 3,
                        'thank_you_page_url': null,
                        'thank_you_title': null,
                        'thank_you_message': null,
                        'thank_you_video_type': null,
                        'thank_you_video_url': null,
                        'thank_you_video_original_url': null,
                        'thank_you_video_width': null,
                        'thank_you_title_show': 0,
                        'thank_you_message_show': 0,
                        'thank_you_video_show': 0,
                        'thank_you_button_text_color': '#fff',
                        'thank_you_button_bg_color': '#3f4f65',
                        'thank_you_button_text': 'Continue',
                        'thank_you_page_active': 1,
                        'thank_you_button_font_size': null,
                        'is_rated_on': 0,
                        'rated_ids': null,
                        'created_at': '2022-12-27T06:13:20.000000Z',
                        'updated_at': '2023-02-09T07:56:47.000000Z',
                        'type': '0',
                        'rated_courses': [],
                        'sections': [],
                        'lessons': [],
                        'authors': [],
                     },
                  },
               ],
               'created_at': '2022-12-27T05:58:21.000000Z',
               'updated_at': '2023-02-09T07:59:03.000000Z',
            },
         ],
      },
      'school_room_components': [
         {
            'id': 21,
            'name': 'Banner',
            'type': 'banner',
            'slug': 'miestro-1672120701NFsB3Qm41cygUvJHGWAYnOEzY5sSIAxo',
            'props': {
               'order': 0,
               'school_banner_src': null,
               'school_show_banner': false,
            },
            'school_room_section_id': 17,
            'subcomponent': [
               {
                  'slug': 'miestro-1672120701GjSSUptuBhjSbhyghjJBUHNwoHY1S4iH',
                  'type': 'banner_title',
                  'name': 'Title',
                  'props': {
                     'text': null,
                     'visibility': true,
                     'isBanner': true,
                     'disabled': true,
                     'paddingBottom': '1',
                     'paddingLeft': '9',
                     'justifyContent': 'flex-end',
                     'alignItems': 'flex-start',
                  },
               },
            ],
            'created_at': '2022-12-27T05:58:21.000000Z',
            'updated_at': '2023-02-09T07:59:03.000000Z',
         },
         {
            'id': 22,
            'name': 'Slider',
            'type': 'slider',
            'slug': 'miestro-1672120701J0pVZaCKD7s7xr9bqgOBLVHXDfAmmu6T',
            'props': {
               'order': 1,
               'visibility': true,
               'school_class_type': 'slider',
            },
            'school_room_section_id': 17,
            'subcomponent': [
               {
                  'slug': 'miestro-1675930096022-undefined',
                  'type': 'class',
                  'name': 'Class',
                  'props': {
                     'order': 0,
                     'picture_src': 'https://miestro-local.s3-us-west-2.amazonaws.com/bd51e1a9098f4898f6cfab183c8e1499/jecej3edh_1675929532426.png',
                     'course_id': 7,
                     'availableDelete': true,
                     'paddingBottom': '1',
                     'paddingLeft': '9',
                     'justifyContent': 'flex-end',
                     'alignItems': 'flex-start',
                     'classType': 'slider',
                  },
                  'subcomponent': [
                     {
                        'slug': 'miestro-1675930506814-1',
                        'type': 'slider_title',
                        'name': 'Class Name',
                        'props': {
                           'visibility': true,
                           'hasVisibility': true,
                           'color': '#ffffff',
                           'fontSize': '56',
                           'fontFamily': 'Avenir Next',
                        },
                     },
                     {
                        'slug': 'miestro-1675930516916-2',
                        'type': 'slider_description',
                        'name': 'Class Description',
                        'props': {
                           'visibility': true,
                           'hasVisibility': true,
                           'color': '#FFFFFF',
                           'fontSize': '18',
                           'fontFamily': 'Avenir Next',
                        },
                     },
                     {
                        'slug': 'miestro-1675930090850-3',
                        'type': 'slider_author',
                        'name': 'Class Author',
                        'props': {
                           'visibility': true,
                           'hasVisibility': true,
                           'color': '#ffffff',
                           'color_bio': '#ffffff',
                           'fontSize': '16',
                           'fontSize_bio': '12',
                           'fontFamily': 'Avenir Next DemiBold',
                           'fontFamily_bio': 'Avenir Next Regular',
                        },
                     },
                     {
                        'slug': 'miestro-1675930461151-4',
                        'type': 'slider_button',
                        'name': 'Class Button',
                        'props': {
                           'visibility': true,
                           'hasVisibility': true,
                           'color': '#FFFFFF',
                           'fontSize': '14',
                           'fontFamily': 'Avenir Next',
                           'width': '239',
                        },
                     },
                  ],
                  'course': {
                     'id': 7,
                     'paypal_product_id': null,
                     'paypal_id': null,
                     'community_id': null,
                     'programm_id': null,
                     'active_landing_url': null,
                     'checkout_landing_id': 0,
                     'name': 'new course 0',
                     'subtitle': null,
                     'is_published': 1,
                     'drip_days': null,
                     'drip_date': null,
                     'publishing_date': '',
                     'drip_type': null,
                     'show_course': 1,
                     'is_duplicated': 1,
                     'duplicate_count': 1,
                     'original_id': 1,
                     'duplication_in_process': 0,
                     'description': '',
                     'author': null,
                     'picture_src': 'http://miestro.loc/images/defaults/thumbnail.png',
                     'thumbnail_image': 'http://miestro.loc/images/defaults/thumbnail.png',
                     'logo': 'http://miestro.loc/images/defaults/course-logo.png',
                     'url': 'new-course10',
                     'landing_url': null,
                     'landing_custom_url': null,
                     'is_custom_url': 0,
                     'bio_description': null,
                     'seo_title': null,
                     'seo_description': null,
                     'seo_image': null,
                     'seo_keywords': null,
                     'landing_page_id': null,
                     'finish_message': null,
                     'show_intro': 0,
                     'intro_video': null,
                     'thank_you_page': 3,
                     'thank_you_page_url': null,
                     'thank_you_title': null,
                     'thank_you_message': null,
                     'thank_you_video_type': null,
                     'thank_you_video_url': null,
                     'thank_you_video_original_url': null,
                     'thank_you_video_width': null,
                     'thank_you_title_show': 0,
                     'thank_you_message_show': 0,
                     'thank_you_video_show': 0,
                     'thank_you_button_text_color': '#fff',
                     'thank_you_button_bg_color': '#3f4f65',
                     'thank_you_button_text': 'Continue',
                     'thank_you_page_active': 1,
                     'thank_you_button_font_size': null,
                     'is_rated_on': 0,
                     'rated_ids': null,
                     'created_at': '2023-02-09T07:56:47.000000Z',
                     'updated_at': '2023-02-09T11:58:25.000000Z',
                     'type': '0',
                     'rated_courses': [],
                     'sections': [],
                     'lessons': [],
                     'authors': [],
                  },
               },
               {
                  'slug': 'miestro-1675929650242-undefined',
                  'type': 'class',
                  'name': 'Class',
                  'props': {
                     'order': 0,
                     'picture_src': 'https://miestro-local.s3-us-west-2.amazonaws.com/bd51e1a9098f4898f6cfab183c8e1499/35ie690g7_1675929527991.png',
                     'course_id': 1,
                     'availableDelete': true,
                     'paddingBottom': '1',
                     'paddingLeft': '9',
                     'justifyContent': 'flex-end',
                     'alignItems': 'flex-start',
                     'classType': 'slider',
                  },
                  'subcomponent': [
                     {
                        'slug': 'miestro-1675930072584-1',
                        'type': 'slider_title',
                        'name': 'Class Name',
                        'props': {
                           'visibility': true,
                           'hasVisibility': true,
                           'color': '#ffffff',
                           'fontSize': '56',
                           'fontFamily': 'Avenir Next',
                        },
                     },
                     {
                        'slug': 'miestro-1675929916378-2',
                        'type': 'slider_description',
                        'name': 'Class Description',
                        'props': {
                           'visibility': true,
                           'hasVisibility': true,
                           'color': '#FFFFFF',
                           'fontSize': '18',
                           'fontFamily': 'Avenir Next',
                        },
                     },
                     {
                        'slug': 'miestro-1675929996682-3',
                        'type': 'slider_author',
                        'name': 'Class Author',
                        'props': {
                           'visibility': true,
                           'hasVisibility': true,
                           'color': '#ffffff',
                           'color_bio': '#ffffff',
                           'fontSize': '16',
                           'fontSize_bio': '12',
                           'fontFamily': 'Avenir Next DemiBold',
                           'fontFamily_bio': 'Avenir Next Regular',
                        },
                     },
                     {
                        'slug': 'miestro-1675929931669-4',
                        'type': 'slider_button',
                        'name': 'Class Button',
                        'props': {
                           'visibility': true,
                           'hasVisibility': true,
                           'color': '#FFFFFF',
                           'fontSize': '14',
                           'fontFamily': 'Avenir Next',
                           'width': '239',
                        },
                     },
                  ],
                  'course': {
                     'id': 1,
                     'paypal_product_id': null,
                     'paypal_id': null,
                     'community_id': null,
                     'programm_id': null,
                     'active_landing_url': null,
                     'checkout_landing_id': 0,
                     'name': 'new course',
                     'subtitle': null,
                     'is_published': 1,
                     'drip_days': null,
                     'drip_date': null,
                     'publishing_date': '',
                     'drip_type': null,
                     'show_course': 1,
                     'is_duplicated': 0,
                     'duplicate_count': 1,
                     'original_id': null,
                     'duplication_in_process': 0,
                     'description': '',
                     'author': null,
                     'picture_src': 'http://miestro.loc/images/defaults/thumbnail.png',
                     'thumbnail_image': 'http://miestro.loc/images/defaults/thumbnail.png',
                     'logo': 'http://miestro.loc/images/defaults/course-logo.png',
                     'url': 'new-course1',
                     'landing_url': null,
                     'landing_custom_url': null,
                     'is_custom_url': 0,
                     'bio_description': null,
                     'seo_title': null,
                     'seo_description': null,
                     'seo_image': null,
                     'seo_keywords': null,
                     'landing_page_id': null,
                     'finish_message': null,
                     'show_intro': 0,
                     'intro_video': null,
                     'thank_you_page': 3,
                     'thank_you_page_url': null,
                     'thank_you_title': null,
                     'thank_you_message': null,
                     'thank_you_video_type': null,
                     'thank_you_video_url': null,
                     'thank_you_video_original_url': null,
                     'thank_you_video_width': null,
                     'thank_you_title_show': 0,
                     'thank_you_message_show': 0,
                     'thank_you_video_show': 0,
                     'thank_you_button_text_color': '#fff',
                     'thank_you_button_bg_color': '#3f4f65',
                     'thank_you_button_text': 'Continue',
                     'thank_you_page_active': 1,
                     'thank_you_button_font_size': null,
                     'is_rated_on': 0,
                     'rated_ids': null,
                     'created_at': '2022-12-27T06:13:20.000000Z',
                     'updated_at': '2023-02-09T07:56:47.000000Z',
                     'type': '0',
                     'rated_courses': [],
                     'sections': [],
                     'lessons': [],
                     'authors': [],
                  },
               },
            ],
            'created_at': '2022-12-27T05:58:21.000000Z',
            'updated_at': '2023-02-09T07:59:03.000000Z',
         },
      ],
   },
   {
      'school_room_section': {
         'id': 18,
         'name': 'Above Content',
         'slug': 'miestro-1672120701SQAKFk9KppO9pcFfwZAk7ZHQc0gcjKFG',
         'school_room_landing_id': 3,
         'props': {
            'bgColor': 'transparent',
            'bgImgSrc': null,
            'duplicated': 'above_content',
            'visibility': true,
            'background_type': 'color',
         },
         'created_at': '2022-12-27T05:58:21.000000Z',
         'updated_at': '2023-02-09T07:59:03.000000Z',
         'school_room_components': [
            {
               'id': 23,
               'name': 'Headline',
               'type': 'text',
               'slug': 'miestro-1672120701SpqM17iYUJ0xWEaTjH0VjiuyO8hC4Nj7',
               'props': {
                  'text': 'Unlimited Access to All Classes',
                  'color': '#1A1A1A',
                  'fontSize': '32',
                  'textAlign': 'center',
                  'paddingTop': '56',
                  'visibility': true,
                  'hasVisibility': true,
                  'paddingBottom': '0',
               },
               'school_room_section_id': 18,
               'subcomponent': null,
               'created_at': '2022-12-27T05:58:21.000000Z',
               'updated_at': '2023-02-09T07:59:03.000000Z',
            },
         ],
      },
      'school_room_components': [
         {
            'id': 23,
            'name': 'Headline',
            'type': 'text',
            'slug': 'miestro-1672120701SpqM17iYUJ0xWEaTjH0VjiuyO8hC4Nj7',
            'props': {
               'text': 'Unlimited Access to All Classes',
               'color': '#1A1A1A',
               'fontSize': '32',
               'textAlign': 'center',
               'paddingTop': '56',
               'visibility': true,
               'hasVisibility': true,
               'paddingBottom': '0',
            },
            'school_room_section_id': 18,
            'subcomponent': null,
            'created_at': '2022-12-27T05:58:21.000000Z',
            'updated_at': '2023-02-09T07:59:03.000000Z',
         },
      ],
   },
   {
      'school_room_section': {
         'id': 19,
         'name': 'Content',
         'slug': 'miestro-1672120701X8OoYSbNL85oZDCT0vPn7dBoHecIscka',
         'school_room_landing_id': 3,
         'props': {
            'bgColor': 'transparent',
            'duplicated': 'content',
            'visibility': true,
            'templateType': 'template3',
         },
         'created_at': '2022-12-27T05:58:21.000000Z',
         'updated_at': '2023-02-09T07:59:03.000000Z',
         'school_room_components': [
            {
               'id': 26,
               'name': 'Class Card',
               'type': 'class_card',
               'slug': 'miestro-1672120701ODVaRfp2PylBHoN70G37ORTqDbPg5hQL',
               'props': {
                  'bgColor': 'transparent',
                  'isContent': true,
                  'duplicated': 'class_card',
               },
               'school_room_section_id': 19,
               'subcomponent': [
                  {
                     'slug': 'miestro-1672120701ZWtB63P8JlVP4xIJ6290Tl3P5khGHtnU',
                     'type': 'sub_text',
                     'name': 'Class Name',
                     'props': {
                        'text': 'Class Name',
                        'color': '#212121',
                        'isContent': true,
                     },
                  },
                  {
                     'slug': 'miestro-1672120701LRTdB2Rl07jYK4J3PovYlAsxcjVtMW1V',
                     'type': 'sub_text',
                     'name': 'Class Name Description',
                     'props': {
                        'text': 'Class Name  Description',
                        'color': '#5F5F5F',
                        'hasVisibility': true,
                        'visibility': false,
                        'isContent': true,
                     },
                  },
                  {
                     'slug': 'miestro-1672120701NQXFZOwe4E1GCYPUFFivAjmKeDMaDYoK',
                     'type': 'sub_text',
                     'name': 'Author',
                     'props': {
                        'text': 'Author',
                        'color': '#5F5F5F',
                        'hasVisibility': true,
                        'visibility': true,
                        'isContent': true,
                     },
                  },
               ],
               'created_at': '2022-12-27T05:58:21.000000Z',
               'updated_at': '2023-02-09T07:59:03.000000Z',
            },
         ],
      },
      'school_room_components': [
         {
            'id': 26,
            'name': 'Class Card',
            'type': 'class_card',
            'slug': 'miestro-1672120701ODVaRfp2PylBHoN70G37ORTqDbPg5hQL',
            'props': {
               'bgColor': 'transparent',
               'isContent': true,
               'duplicated': 'class_card',
            },
            'school_room_section_id': 19,
            'subcomponent': [
               {
                  'slug': 'miestro-1672120701ZWtB63P8JlVP4xIJ6290Tl3P5khGHtnU',
                  'type': 'sub_text',
                  'name': 'Class Name',
                  'props': {
                     'text': 'Class Name',
                     'color': '#212121',
                     'isContent': true,
                  },
               },
               {
                  'slug': 'miestro-1672120701LRTdB2Rl07jYK4J3PovYlAsxcjVtMW1V',
                  'type': 'sub_text',
                  'name': 'Class Name Description',
                  'props': {
                     'text': 'Class Name  Description',
                     'color': '#5F5F5F',
                     'hasVisibility': true,
                     'visibility': false,
                     'isContent': true,
                  },
               },
               {
                  'slug': 'miestro-1672120701NQXFZOwe4E1GCYPUFFivAjmKeDMaDYoK',
                  'type': 'sub_text',
                  'name': 'Author',
                  'props': {
                     'text': 'Author',
                     'color': '#5F5F5F',
                     'hasVisibility': true,
                     'visibility': true,
                     'isContent': true,
                  },
               },
            ],
            'created_at': '2022-12-27T05:58:21.000000Z',
            'updated_at': '2023-02-09T07:59:03.000000Z',
         },
      ],
   },
   {
      'school_room_section': {
         'id': 20,
         'name': 'Below Content',
         'slug': 'miestro-1672120701xjyvatQrbOntE2f1iNKKf524wYuvop6M',
         'school_room_landing_id': 3,
         'props': {
            'bgColor': 'transparent',
            'bgImgSrc': null,
            'duplicated': 'below_content',
            'visibility': true,
            'background_type': 'color',
         },
         'created_at': '2022-12-27T05:58:21.000000Z',
         'updated_at': '2023-02-09T07:59:03.000000Z',
         'school_room_components': [],
      },
      'school_room_components': [],
   },
   {
      'school_room_section': {
         'id': 21,
         'name': 'Footer',
         'slug': 'miestro-1672120701i5yGn28zy4YNTkCsnRGSzlZhhF5nfR3u',
         'school_room_landing_id': 3,
         'props': {
            'bgColor': '#272727',
            'bgImgSrc': null,
            'duplicated': 'footer',
            'visibility': true,
            'background_type': 'color',
         },
         'created_at': '2022-12-27T05:58:21.000000Z',
         'updated_at': '2023-02-09T07:59:03.000000Z',
         'school_room_components': [
            {
               'id': 27,
               'name': 'Privacy Policy',
               'type': 'text',
               'slug': 'miestro-1672120701BILof5XwabWBYAJPx2jdfqsbx3Q9lR4e',
               'props': {
                  'text': 'Privacy Policy',
                  'color': '#ffffff',
                  'bgColor': '#272727',
                  'disabled': true,
                  'fontSize': '16',
                  'isFooter': true,
                  'visibility': true,
                  'hasVisibility': true,
               },
               'school_room_section_id': 21,
               'subcomponent': null,
               'created_at': '2022-12-27T05:58:21.000000Z',
               'updated_at': '2023-02-09T07:59:03.000000Z',
            },
            {
               'id': 28,
               'name': 'Terms',
               'type': 'text',
               'slug': 'miestro-1672120701mzVS1bNFJopJgIGvqOnBdfpJ4e4SwbiS',
               'props': {
                  'text': 'Terms',
                  'color': '#ffffff',
                  'bgColor': '#272727',
                  'disabled': true,
                  'fontSize': '16',
                  'isFooter': true,
                  'visibility': true,
                  'hasVisibility': true,
               },
               'school_room_section_id': 21,
               'subcomponent': null,
               'created_at': '2022-12-27T05:58:21.000000Z',
               'updated_at': '2023-02-09T07:59:03.000000Z',
            },
            {
               'id': 29,
               'name': 'Links',
               'type': 'links',
               'slug': 'miestro-1672120701sDkmpAANpmAIPADGYDeWVpehdKRzQ23S',
               'props': {
                  'isLinks': true,
               },
               'school_room_section_id': 21,
               'subcomponent': [],
               'created_at': '2022-12-27T05:58:21.000000Z',
               'updated_at': '2023-02-09T07:59:03.000000Z',
            },
            {
               'id': 30,
               'name': 'Copyright',
               'type': 'text',
               'slug': 'miestro-1672120701g3kvAoeYMA11ZbOsQGYVdWWiZIn65wdp',
               'props': {
                  'text': 'Copyright © 2023 by rud',
                  'color': '#ffffff',
                  'bgColor': '#272727',
                  'fontSize': '16',
                  'isFooter': true,
                  'visibility': true,
                  'hasVisibility': true,
               },
               'school_room_section_id': 21,
               'subcomponent': null,
               'created_at': '2022-12-27T05:58:21.000000Z',
               'updated_at': '2023-02-09T07:59:03.000000Z',
            },
         ],
      },
      'school_room_components': [
         {
            'id': 27,
            'name': 'Privacy Policy',
            'type': 'text',
            'slug': 'miestro-1672120701BILof5XwabWBYAJPx2jdfqsbx3Q9lR4e',
            'props': {
               'text': 'Privacy Policy',
               'color': '#ffffff',
               'bgColor': '#272727',
               'disabled': true,
               'fontSize': '16',
               'isFooter': true,
               'visibility': true,
               'hasVisibility': true,
            },
            'school_room_section_id': 21,
            'subcomponent': null,
            'created_at': '2022-12-27T05:58:21.000000Z',
            'updated_at': '2023-02-09T07:59:03.000000Z',
         },
         {
            'id': 28,
            'name': 'Terms',
            'type': 'text',
            'slug': 'miestro-1672120701mzVS1bNFJopJgIGvqOnBdfpJ4e4SwbiS',
            'props': {
               'text': 'Terms',
               'color': '#ffffff',
               'bgColor': '#272727',
               'disabled': true,
               'fontSize': '16',
               'isFooter': true,
               'visibility': true,
               'hasVisibility': true,
            },
            'school_room_section_id': 21,
            'subcomponent': null,
            'created_at': '2022-12-27T05:58:21.000000Z',
            'updated_at': '2023-02-09T07:59:03.000000Z',
         },
         {
            'id': 29,
            'name': 'Links',
            'type': 'links',
            'slug': 'miestro-1672120701sDkmpAANpmAIPADGYDeWVpehdKRzQ23S',
            'props': {
               'isLinks': true,
            },
            'school_room_section_id': 21,
            'subcomponent': [],
            'created_at': '2022-12-27T05:58:21.000000Z',
            'updated_at': '2023-02-09T07:59:03.000000Z',
         },
         {
            'id': 30,
            'name': 'Copyright',
            'type': 'text',
            'slug': 'miestro-1672120701g3kvAoeYMA11ZbOsQGYVdWWiZIn65wdp',
            'props': {
               'text': 'Copyright © 2023 by rud',
               'color': '#ffffff',
               'bgColor': '#272727',
               'fontSize': '16',
               'isFooter': true,
               'visibility': true,
               'hasVisibility': true,
            },
            'school_room_section_id': 21,
            'subcomponent': null,
            'created_at': '2022-12-27T05:58:21.000000Z',
            'updated_at': '2023-02-09T07:59:03.000000Z',
         },
      ],
   },
];
