
const slug = () => {
   function s4() {
      return new Date().getTime() + Math.floor(Math.random() * 1000000);
   }
   return `miestro-${ s4() }`;
};

const generateTemplate = (inputs) => {
   return {
      sections: [
         {
            upsell_section: {
               slug: slug(),
               type: 'Main',
               name: 'Main Background',
               props: {
                  duplicated: 'main_background',
                  bgColor: '#fff',
               },
            },
            upsell_components: [
               {
                  slug: slug(),
                  type: 'image',
                  name: 'Logo',
                  props: {
                     image_src: '',
                     order: 0,
                     paddingTop: 0,
                     paddingLeft: 0,
                     paddingBottom: 0,
                     paddingRight: 0,
                     width: 30,
                     justifyContent: 'center',
                     visibility: true,
                     borderRadius: 0,
                  },
               },
               {
                  slug: slug(),
                  type: 'product',
                  name: 'Product',
                  props: {
                     margin: '32px 0px 32px 0px',
                     order: 1,
                     paddingTop: 12,
                     paddingBottom: 12,
                     paddingLeft: 12,
                     paddingRight: 12,
                     bgColor: '#F7FCFC',
                  },
               },
               {
                  slug: slug(),
                  type: 'text',
                  name: 'Headline',
                  props: {
                     order: 2,
                     text: inputs.headline,
                     textAlign: 'center',
                     lineHeight: 130,
                     fontWeight: '500',
                     fontSize: 28,
                     paddingTop: 0,
                     paddingLeft: 0,
                     paddingBottom: 24,
                     paddingRight: 0,
                     color: '#131F1E',
                     bgColor: '',
                     width: 100,
                  },
               },
               {
                  slug: slug(),
                  type: 'text',
                  name: 'Description',
                  props: {
                     order: 3,
                     text: inputs.description,
                     fontWeight: '400',
                     fontSize: 14,
                     paddingTop: 0,
                     paddingLeft: 0,
                     paddingBottom: 24,
                     paddingRight: 0,
                     lineHeight: 168,
                     textAlign: 'center',
                     color: '#131F1E',
                     bgColor: '',
                     width: 100,
                  },
               },
               {
                  slug: slug(),
                  type: 'pricing',
                  name: 'Pricing',
                  props: {
                     order: 4,
                     background: 'inherit',
                     paddingTop: '24',
                     paddingBottom: '24',
                     paddingLeft: '24',
                     paddingRight: '24',
                  },
                  subcomponents: [
                     {
                        slug: slug(),
                        type: 'text',
                        name: 'Order Summary',
                        props: {
                           text: 'Order Summary',
                           paddingTop: 0,
                           paddingLeft: 0,
                           paddingBottom: 16,
                           paddingRight: 0,
                           fontWeight: '400',
                           fontSize: 18,
                           lineHeight: 153,
                           textAlign: 'start',
                           bgColor: '',
                           color: '#131F1E',
                           width: 100,
                        },
                     },
                     {
                        slug: slug(),
                        type: 'product-price',
                        name: 'Product Price',
                        props: {
                        },
                     },
                     {
                        slug: slug(),
                        type: 'due',
                        name: 'Due Today',
                        props: {
                           margin: '16px 0px 8px 0px',
                        },
                     },
                     {
                        slug: slug(),
                        type: 'text',
                        name: 'Order Text',
                        props: {
                           text: 'Your subscription will automatically renewed until cancelled. You can cancel automatic renewal in your account settings any time.',
                           fontWeight: '400',
                           fontSize: 12,
                           paddingTop: 0,
                           paddingLeft: 0,
                           paddingBottom: 24,
                           paddingRight: 0,
                           color: '#727978',
                           lineHeight: 150,
                           bgColor: '',
                           width: 100,
                           maxWidth: 100,
                           textAlign: 'start',
                        },
                     },
                  ],
               },
               {
                  slug: slug(),
                  type: 'guarantee',
                  name: 'Guarantee',
                  props: {
                     order: 4,
                     background: '#F0F2F2',
                     paddingTop: '16',
                     paddingBottom: '16',
                     paddingLeft: '24',
                     paddingRight: '24',
                     visibility: true,
                  },
                  subcomponents: [
                     {
                        slug: slug(),
                        type: 'text',
                        name: 'Days',
                        props: {
                           text: '30 Days',
                           paddingTop: 0,
                           paddingLeft: 0,
                           paddingBottom: 0,
                           paddingRight: 0,
                           fontWeight: '400',
                           fontSize: 14,
                           lineHeight: 168,
                           isIconText: true,
                           iconColor: '#444C4B',
                           iconName: 'MoneyBackGuaranteeM',
                           textAlign: 'start',
                           bgColor: '',
                           color: '#444C4B',
                           width: 100,
                        },
                     },
                     {
                        slug: slug(),
                        type: 'text',
                        name: 'Money Back',
                        props: {
                           text: 'Money-Back Guarantee',
                           fontWeight: '400',
                           fontSize: 14,
                           paddingTop: 0,
                           paddingLeft: 0,
                           paddingBottom: 0,
                           paddingRight: 0,
                           color: '#444C4B',
                           lineHeight: 168,
                           bgColor: '',
                           width: 100,
                           textAlign: 'end',
                        },
                     },
                  ],
               },
               {
                  slug: slug(),
                  type: 'button',
                  name: 'Button Purcahse',
                  props: {
                     order: 5,
                     isAction: false,
                     isBlank: true,
                     inner: inputs.purchase_button,
                     theme: 'primary',
                     background: '#24554E',
                     color: 'white',
                     paddingTop: '12',
                     paddingBottom: '12',
                     paddingLeft: '16',
                     visibility: true,
                     justifyContent: 'center',
                     url: '',
                     paddingRight: '16',
                     width: '30',
                     margin: '32px 0px 12px 0px',
                  },
               },
               {
                  slug: slug(),
                  type: 'button',
                  name: 'Button Cancel',
                  props: {
                     order: 6,
                     isAction: false,
                     isBlank: true,
                     url: '',
                     inner: inputs.cancel_button,
                     theme: 'inherit',
                     paddingTop: '12',
                     background: 'inherit',
                     paddingBottom: '12',
                     paddingLeft: '16',
                     justifyContent: 'center',
                     paddingRight: '16',
                     color: '#131F1E',
                     visibility: true,
                     width: '100',
                     margin: '0px 0px 0px 0px',
                  },
               },
            ],
         },
         {
            upsell_section: {
               slug: slug(),
               type: 'Bottom',
               name: 'Contact',
               props: {
                  duplicated: 'contact',
                  visibility: true,
               },
            },
            upsell_components: [
               {
                  slug: slug(),
                  type: 'text',
                  name: 'Help',
                  props: {
                     order: 0,
                     text: 'Need Help? Contact Support',
                     fontWeight: '500',
                     fontSize: 16,
                     paddingTop: 0,
                     paddingLeft: 0,
                     paddingBottom: 16,
                     paddingRight: 0,
                     color: '#444C4B',
                     lineHeight: 148,
                     bgColor: '',
                     width: 100,
                     textAlign: 'center',
                  },
               },
               {
                  slug: slug(),
                  type: 'contactBottom',
                  name: 'Bottom',
                  props: {
                     order: 1,
                     paddingTop: 16,
                     paddingLeft: 0,
                     paddingRight: 0,
                     paddingBottom: 0,
                  },
                  subcomponents: [
                     {
                        slug: slug(),
                        type: 'text',
                        name: 'Number',
                        props: {
                           text: '1-844-542-5275',
                           fontWeight: '400',
                           fontSize: 16,
                           paddingTop: 16,
                           paddingLeft: 0,
                           paddingBottom: 0,
                           paddingRight: 38,
                           color: '#444C4B',
                           lineHeight: 148,
                           bgColor: '',
                           textAlign: 'end',
                           isIconText: true,
                           iconColor: '#444C4B',
                           iconName: 'UpsellNumberM',
                        },
                     },
                     {
                        slug: slug(),
                        type: 'text',
                        name: 'Mail',
                        props: {
                           text: '1-844-542-5275',
                           fontWeight: '400',
                           fontSize: 16,
                           paddingTop: 16,
                           paddingLeft: 0,
                           paddingBottom: 0,
                           paddingRight: 0,
                           color: '#444C4B',
                           lineHeight: 148,
                           bgColor: '',
                           textAlign: 'center',
                           isIconText: true,
                           iconColor: '#444C4B',
                           iconName: 'UpsellMailM',
                        },
                     },
                  ],
               },
            ],
         },
      ],
   };
};

export default generateTemplate;
