import React from 'react';

export const terms = [
   'Company TERMS AND CONDITIONS OF USE',
   <br />, <br />,
   'Terms',
   <br />, <br />,
   'By accessing this website, you agree to be bound by these Terms and Conditions of Use, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with these terms, you are prohibited from using or accessing this site. All materials contained on Company’s site are protected by applicable copyright and trademark laws.',
   <br />, <br />,
   'Use License and Acceptable Use',
   <br />, <br />,
   'Unless otherwise stated, Company owns the intellectual property rights in the website and material on the website. Subject to the license below, all these rights are reserved.',
   <br />, <br />,
   'You may view, download, and print pages or other content (information or software) from the website for your own personal, non-commercial use, subject to the restrictions in these Terms and Conditions. This is the grant of a license, not a transfer of title, under which you may not:',
   <br />, <br />,
   'modify or duplicate the materials;',
   <br />,
   'use the materials for any commercial purpose, or for any public display (commercial or non- commercial);',
   <br />,
   'sell, rent, or sub-license material from the website;',
   <br />,
   'republish material from this website (including republication on another website);',
   <br />,
   'attempt to decompile or reverse engineer any software contained on Company’s website;',
   <br />,
   'remove any copyright or other proprietary notations from the materials; or',
   <br />,
   'transfer or “mirror” the materials to another person or any other server.',
   <br />, <br />,
   'This license shall automatically terminate upon violation of any of these restrictions and may be terminated by Company at any time. Upon termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.',
   <br />, <br />,
   'You must not use this website in any way that causes or may cause damage to the website or impairment of the availability or accessibility of the website; or in any way which is in connection with any unlawful, illegal, fraudulent, or harmful purpose or activity.',
   <br />, <br />,
   'You must not use this website to copy, store, host, transmit, send, use, publish, or distribute any material which consists of (or is linked to) any spyware, computer virus, or other malicious computer software.',
   <br />, <br />,
   'User Content',
   <br />, <br />,
   'As used in these Terms and Conditions, “user content” means material (including without limitation text, images, audio material, video material, and audio-visual material) that you submit to this website, for whatever purpose.',
   <br />, <br />,
   'Your user content must not be illegal or unlawful, must not infringe any third party’s legal rights, and must not be capable of giving rise to legal action whether against you, Company, or a third party (under any applicable law).',
   <br />, <br />,
   'You must not submit any user content to the website that is or has ever been the subject of any threatened or actual legal proceedings or complaint.',
   <br />, <br />,
   'Company reserves the right to edit or remove any material submitted to, hosted by, or published upon this website, or stored on Company’s servers.',
   <br />, <br />,
   'Notwithstanding Company’s rights under these Terms and Conditions in relation to user content, Company does not undertake the responsibility to monitor the submission to or publication of such content on this website.',
   <br />, <br />,
   'Disclaimer',
   <br />, <br />,
   'The materials on Company’s website are provided “as is” without any representations or warranties, expressed or implied, and Company hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.',
   <br />, <br />,
   'Company does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.',
   <br />, <br />,
   'Company does not warrant that this website will be constantly available, or available at all, or that the information on this website is complete, true, accurate, or non-misleading.',
   <br />, <br />,
   'Company has not reviewed all of the sites linked to its website and is not responsible for the contents of any linked site. The inclusion of any link does not imply endorsement by Company of the site. Use of any linked website is at the user’s own risk.',
   <br />, <br />,
   'Limitations',
   <br />, <br />,
   'In no event shall Company be liable for any damages (including, without limitation, damages for any business losses, loss of revenue, income, profits or anticipated savings, loss of contracts or business relationships, loss of reputation or goodwill, or loss or corruption of information or data) arising out of the use or inability to use the materials on Company’s website or the ability or inability to gain access to Company’s website.',
   <br />, <br />,
   'These limitations apply even if Company or a Company authorized representative has been notified orally or in writing of the possibility of such damage.',
   <br />, <br />,
   'Note that some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, and thus, these limitations may not apply to you.',
   <br />, <br />,
   'Revisions',
   <br />, <br />,
   'The materials appearing on Company’s website could include technical, typographical, or photographic errors. Company does not warrant that any of the materials on its website are accurate, complete, or current. Company may make changes to the materials contained on its website at any time without notice. Company does not, however, make any commitment to update the materials.',
   <br />, <br />,
   'Company may revise these terms of use for its website at any time without notice. By using this website, you are agreeing to be bound by the then current version of these Terms and Conditions of Use.',
   <br />, <br />,
   'Governing Law',
   <br />, <br />,
   'Any claim relating to Company’s website shall be governed by the laws of the State of Georgia. Any disputes relating to these Terms and Conditions will be subject to the jurisdiction of the courts of the State of Georgia.',
];

export const privacy = [
   'Company’S PRIVACY POLICY',
   <br />, <br />,
   'Your privacy is important to Company. This Privacy Policy provides information about how Company collects, uses, maintains, and discloses information collected from users of the site.',
   <br />, <br />,
   'Personal Information',
   <br />, <br />,
   'Company may collect personal information from users in a variety of ways, including, but not limited to, the following:',
   <br />, <br />,
   'when users visit our site;',
   <br />,
   'when users register on the site;',
   <br />,
   'when users subscribe to the blog or newsletter; or',
   <br />,
   'in connection with other activities, services, features, or resources Company makes available on the site.',
   <br />, <br />,
   'Company may collect users’ personal information only if users voluntarily submit this information to Company. Users are able to refuse to supply personal information, but it may prevent them from accessing certain site features.',
   <br />, <br />,
   'Non-Personal Information',
   <br />, <br />,
   'Company may collect non-personal identification information about users when they interact with the site. This category of information may include the browser name, the type of computer, and technical information about the user’s connection to the site (including the operating system and the internet service provider).',
   <br />, <br />,
   'Web Browser Cookies',
   <br />, <br />,
   'Company may use cookies to enhance the user experience on the site. A user’s web browser will place cookies on their hard drive for record keeping or to track information about the user. Users are able to refuse cookies via their browser settings. In this case, some parts of Company’s site may not function properly.',
   <br />, <br />,
   'Using Collected Information',
   <br />, <br />,
   'Company does not sell, trade, or rent any user personal information to others. Rather, Company may collect and use personal information for the following purposes:',
   <br />, <br />,
   'To better support the needs of our users.',
   <br />,
   'To help us better understand how our site and services are used and how to make improvements.',
   <br />,
   'To send emails to users if they have voluntarily provided their email address. Emails could be sent in response to an order placed, to respond to inquiries received, or in response to an opt-in to our mailing list. A user can unsubscribe at any time.',
   <br />, <br />,
   'Protecting Your Information',
   <br />, <br />,
   'Company stores all personal information provided by users on secure servers. Company has put in place reasonable precautions and security measures to protect against and prevent unauthorized access, alteration, disclosure, or destruction of your personal information stored on the site.',
   <br />, <br />,
   'Third-Party Websites',
   <br />, <br />,
   'This site may contain links to other websites. Company does not control the content or links that appear on these third-party sites and is not responsible for the privacy policies or practices of any third-party site.',
   <br />, <br />,
   'Privacy Policy Updates',
   <br />, <br />,
   'Company has the discretion to update this privacy policy at any time. Company encourages its users to check this page occasionally to stay updated with any changes.',
   <br />, <br />,
   'It is the responsibility of each user to periodically review this privacy policy to become aware of any modifications.',
   <br />, <br />,
   'Your Acceptance of These Terms',
   <br />, <br />,
   'By accessing and using the Company site, you agree to and accept this policy. If you do not agree, please do not use the site. After posting any changes to this policy, your continued use of the site will be considered as your acceptance of those changes.',
];
